export const APP_LANGUAGE_CONSTANTS = {
    APP_LANGUAGE_SCREEN: 'APP_LANGUAGE_SCREEN',
    CONTENT_LANGUAGE_SCREEN: 'CONTENT_LANGUAGE_SCREEN',
    ENGLISH_LOCALIZATION_KEY: 'en',
    TAMIL_LOCALIZATION_KEY: 'ta',
    TELUGU_LOCALIZATION_KEY: 'te',
    ENGLISH: 'English',
    TAMIL: 'Tamil',
    TELUGU: 'Telugu',
    APP_LANGUAGE_ENGLISH_DESC: 'You will be reading the content titles & more in this language',
    TELUGU_REGIONAL: 'తెలుగు',
    APP_LANGUAGE_TELUGU_REGIONAL_DESC: 'మీరు ఈ భాషలోని మొత్తం కంటెంట్‌ను చూస్తారు',
    TAMIL_REGIONAL: 'தமிழ்',
    APP_LANGUAGE_TAMIL_REGIONAL_DESC: 'இந்த மொழியில் உள்ளடக்க தலைப்புகள் மற்றும் பலவற்றை நீங்கள் படிப்பீர்கள்',
    CONTENT_LANGUAGE_TELUGU: 'మీరు ఈ భాషలోని మొత్తం కంటెంట్‌ను చూస్తారు',
    CONTENT_LANGUAGE_TAMIL: 'இந்த மொழியில் எல்லா உள்ளடக்கத்தையும் காண்பீர்கள்',
    READ: 'Read ',
    CONTENT: 'Content',
    IN_ENGLISH: ' in English',
    READ_TELUGU: 'తెలుగులో ',
    CONTENT_TELUGU: 'కంటెంట్',
    IN_TELUGU: 'చదవండి ',
    READ_TAMIL: 'தமிழில் ',
    CONTENT_TAMIL: 'உள்ளடக்கத்தை',
    IN_TAMIL: ' படியுங்கள்',
    APP_LANGUAGE_TELUGU_TITLE: 'తెలుగులో కంటెంట్ చదవండి',
    APP_LANGUAGE_TAMIL_TITLE: 'தமிழில் உள்ளடக்கத்தை படியுங்கள்',
    APP_LANGUAGE_TAMIL_HIGHLIGHT_TEXT1: 'உள்ளடக்கத்தை',
    APP_LANGUAGE_TELUGU_HIGHLIGHT_TEXT1: 'కంటెంట్',
};
