module.exports = {
    out: './docs/dist/',
    platform: 'bitbucket',
    theme: 'markdown',
    module: 'es2015',
    includes: './src/components/**/src',
    exclude: ['**/__tests__/**/*', '**/*.types.ts'],
    mode: 'file',
    excludeExternals: true,
    excludeNotExported: true,
    excludePrivate: true,
    excludeProtected: true,
    target: 'ES6',
    tsconfig: './tsconfig.json',
    ignoreCompilerErrors: true,
};
