export const LOGIN_ERROR_CODES = {
    LOGIN_NO_USER_FOUND: 'eV2327',
    LOGIN_INVALID_CREDENTIALS: 'eV2134',
    LOGIN_VERIFY_YOUR_ACOUNT: 'eV2371',
};

export const SIGNUP_ERROR_CODES = {
    SIGNUP_USER_ALREADY_EXIST: 'eV1062',
    SIGNUP_ENTER_VALID_EMAIL: 'eV1058',
};

export const API_STATUS = {
    LOADING: 'loading',
    ERROR: 'error',
    FETCHED: 'fetched',
    ON_UPDATE: 'ON_UPDATE',
};

export const PROFILE_ACTION_TYPES = {
    UPDATE_PROFILES: 'UPDATE_PROFILES',
    UPDATE_ACTIVE_PROFILE: 'UPDATE_ACTIVE_PROFILE',
    UPDATE_APP_LANG: 'UPDATE_APP_LANG',
    UPDATE_CONTENT_LANG: 'UPDATE_CONTENT_LANG',
    PROFILE_ERROR: 'PROFILE_ERROR',
    LANGUAGE_ERROR: 'LANGUAGE_ERROR',
    CLEANUP_PROFILES: 'CLEANUP_PROFILES',
};
