export const NAVIGATION_TYPE = {
    SEARCH: 'Search',
    SETTINGS: 'Settings',
    CREDITS: 'Credits',
    BROWSE: 'Browse',
    LOADING: 'Loading',
    APP_TABS: 'AppTabsScreen',
    AUTH: 'AuthStackScreen',
    AUTH_HOME: 'AuthHome',
    AUTH_SIGN_UP: 'SignUp',
    SIGN_UP_PROFILE_TV: 'SIGNUP_PROFILE_TV',
    AUTH_SIGN_IN: 'SignIn',
    AUTH_SIGN_IN_TV: 'LoginTV',
    AUTH_FORGOT_PASSWORD: 'ForgotPassword',
    AUTH_FORGOT_PASSWORD_OTP: 'ForgotPasswordOtp',
    AUTH_FORGOT_PASSWORD_RESET: 'ForgotPasswordReset',
    CONTENT_DETAILS: 'Details',
    EPISODE_DETAILS: 'Episodes',
    COLLECTIONS: 'Collections',
    COLLECTIONS_GRID: 'CollectionsGrid',
    PLAYER: 'Player',
    STOREFRONT_VIEWALL_TV: 'StorefrontViewallTV',
    CONTINUE_SUBSCRIPTION: 'ContinueSubscription',
    PURCHASE_SUBSCRIPTION: 'PurchaseSubscription',
    PURCHASE_CONFIRMATION: 'PurchaseConfirmation',
    ONBOARDING_INTRO: 'OnboardingIntro',
    ONBOARDING_CREDITS_BUTTON: 'OnboardingCreditsButton',
    ONBOARDING_SELECT_Content: 'OnboardingSelectContent',
    ONBOARDING_REDEEM_Content: 'OnboardingRedeemContent',
    ONBOARDING_RULES_INTRO: 'OnboardingRulesIntro',
    ONBOARDING_FREE_CREDITS: 'OnboardingFreeCredits',

    MY_CONTENT: 'My Content',
    SERIES_DOWNLOAD: 'SeriesDownload',
    CHANNEL: 'Channel',

    //SettingStackScreen
    ENVIRONMENT: 'EnvScreen',
    PROFILE: 'Profile',
    USER_PROFILE: 'UserProfile',
    PREFERENCES: 'Preferences',
    BILLING_PAYMENTS: 'BillingPayments',
    MANAGE_DEVICES: 'ManageDevices',
    HELP: 'Help',
    PRIVACY_POLICY: 'PrivacyPolicy',
    TERMS_CONDITIONS: 'TermsCondition',
    CREDITS_WALKTHROUGH: 'CreditsWalkthrough',
    CREDITS_WALKTHROUGH_STEP_2: 'CreditsWalkthroughStep2',
    CREDITS_WALKTHROUGH_STEP_3: 'CreditsWalkthroughStep3',
    CREDITS_WALKTHROUGH_END: 'CreditsWalkthroughEnd',
    LOGOUT: 'Logout',
    BROWSE_WEBVIEW: 'BrowseWebView',
    FAQ: 'FAQ',
    CONTENT_AVAILABILITY: 'ContentAvailability',
    CONTACT: 'Contact',
    ACCOUNT: 'Account',
    LEGAL: 'Legal',
};
