export const NAVIGATION_TYPE = {
    SEARCH: 'Search',
    SETTINGS: 'Settings',
    MENU: 'Menu',
    CREDITS: 'Credits',
    BROWSE: 'Browse',
    LOADING: 'Loading',
    APP_TABS: 'AppTabsScreen',
    AUTH: 'AuthStackScreen',
    AUTH_HOME: 'AuthHome',
    AUTH_SIGN_UP: 'SignUp',
    AUTH_SIGN_IN: 'SignIn',
    AUTH_VERIFY_OTP: 'VerifyOTP',
    AUTH_VALIDATE_USER: 'AUTH_VALIDATE_USER',
    AUTH_FORGOT_PASSWORD: 'ForgotPassword',
    AUTH_FORGOT_PASSWORD_OTP: 'ForgotPasswordOtp',
    AUTH_FORGOT_PASSWORD_RESET: 'ForgotPasswordReset',
    CONTENT_DETAILS: 'Details',
    EPISODE_DETAILS: 'Episodes',
    COLLECTIONS: 'Collections',
    COLLECTIONS_GRID: 'CollectionsGrid',
    PLAYER: 'Player',
    CONTINUE_SUBSCRIPTION: 'ContinueSubscription',
    PURCHASE_SUBSCRIPTION: 'PurchaseSubscription',
    PURCHASE_CONFIRMATION: 'PurchaseConfirmation',
    ONBOARDING_INTRO: 'OnboardingIntro',
    ONBOARDING_CREDITS_BUTTON: 'OnboardingCreditsButton',
    ONBOARDING_SELECT_Content: 'OnboardingSelectContent',
    ONBOARDING_REDEEM_Content: 'OnboardingRedeemContent',
    ONBOARDING_RULES_INTRO: 'OnboardingRulesIntro',
    ONBOARDING_FREE_CREDITS: 'OnboardingFreeCredits',
    MARKETING_ONBOARD: 'MarketingOnboard',
    CONTENT_LANGUAGE_SELECTION: 'LanguageSelectionScreen',
    APP_LANGUAGE_SELECTION: 'AppLanguageSelectionScreen',
    SWITCH_LANGUAGE: 'SwitchLanguageScreen',

    MY_CONTENT: 'MyContent',
    SERIES_DOWNLOAD: 'SeriesDownload',
    DOWNLOADS: 'Downloads',
    WATCHLIST: 'Watchlist',

    //SettingStackScreen
    ENVIRONMENT: 'EnvScreen',
    PROFILE: 'Profile',
    USER_PROFILE: 'UserProfile',
    PROFILE_SELECTION: 'profileSelection',
    MANAGE_PROFILE: 'manageProfile',
    EDIT_PROFILE: 'editProfile',
    PREFERENCES: 'Preferences',
    LANGUAGE_PREFERENCES: 'LanguagePreference',
    BILLING_PAYMENTS: 'BillingPayments',
    MANAGE_DEVICES: 'ManageDevices',
    HELP: 'Help',
    PRIVACY_POLICY: 'PrivacyPolicy',
    TERMS_CONDITIONS: 'TermsCondition',
    CREDITS_WALKTHROUGH: 'CreditsWalkthrough',
    LOGOUT: 'Logout',
    MY_PURCHASES: 'MyPurchases',
    LINK_A_DEVICE: 'LinkDevice',
    MENU_SETTINGS: 'MenuSettings',
    REFER_AND_EARN: 'ReferAndEarn',
    SUBSCRIPTION_DETAILS: 'SubscriptionDetails',
    PARENTAL_CONTROLS: 'ParentalControls',
    APP_SETTINGS: 'AppSettings',

    // OfflineStackScreen
    OFFLINE: 'offline',
};
