export const NAVIGATION_TYPE = {
    SEARCH: 'Search',
    SETTINGS: 'Settings',
    CREDITS: 'Credits',
    BROWSE: 'Browse',
    LOADING: 'Loading',
    APP_TABS: 'AppTabsScreen',
    AUTH: 'AuthStackScreen',
    AUTH_HOME: 'AuthHome',
    AUTH_SIGN_UP: 'SignUp',
    AUTH_SIGN_IN: 'SignIn',
    AUTH_FORGOT_PASSWORD: 'ForgotPassword',
    AUTH_FORGOT_PASSWORD_OTP: 'ForgotPasswordOtp',
    AUTH_FORGOT_PASSWORD_RESET: 'ForgotPasswordReset',
    PLAN_INFO: 'PlanInfo',
    CONTENT_DETAILS: 'Details',
    EPISODE_DETAILS: 'Episodes',
    COLLECTIONS: 'Collections',
    COLLECTIONS_GRID: 'CollectionsGrid',
    STOREFRONT_VIEWALL: 'StorefrontViewall',
    PLAYER: 'Player',
    CONTINUE_SUBSCRIPTION: 'ContinueSubscription',
    PURCHASE_SUBSCRIPTION: 'PurchaseSubscription',
    PURCHASE_CONFIRMATION: 'PurchaseConfirmation',
    ONBOARDING_INTRO: 'OnboardingIntro',
    ONBOARDING_CREDITS_BUTTON: 'OnboardingCreditsButton',
    ONBOARDING_SELECT_Content: 'OnboardingSelectContent',
    ONBOARDING_REDEEM_Content: 'OnboardingRedeemContent',
    ONBOARDING_RULES_INTRO: 'OnboardingRulesIntro',
    ONBOARDING_FREE_CREDITS: 'OnboardingFreeCredits',

    MY_COLLECTION_TAB: 'My Collection',
    MY_CONTENT: 'MyContent',
    MY_CONTENT_TABS: 'My Content',
    SERIES_DOWNLOAD: 'SeriesDownload',

    //SettingStackScreen
    ENVIRONMENT: 'EnvScreen',
    PROFILE: 'Profile',
    USER_PROFILE: 'UserProfile',
    PREFERENCES: 'Preferences',
    BILLING_PAYMENTS: 'BillingPayments',
    MANAGE_DEVICES: 'ManageDevices',
    HELP: 'Help',
    PRIVACY_POLICY: 'PrivacyPolicy',
    TERMS_CONDITIONS: 'TermsCondition',
    CREDITS_WALKTHROUGH: 'CreditsWalkthrough',
    LOGOUT: 'Logout',
    BROWSE_WEBVIEW: 'BrowseWebView',
    FAQ: 'FAQ',
    CONTENT_AVAILABILITY: 'ContentAvailability',
    CONTACT: 'Contact',
};
