export const AUTOMATION_TEST_ID = {
    PROCEED_BUTTON: 'PROCEED_BUTTON',
    TEXT_INPUT_BOX_EMAIL_ID: 'TEXT_INPUT_BOX_EMAIL_ID',
    TEXT_INPUT_BOX_PASSWORD: 'TEXT_INPUT_BOX_PASSWORD',
    FORGOT_PASSWORD: 'FORGOT_PASSWORD',
    PRIMARY_BUTTON: 'PRIMARY_BUTTON',
    RESEND_OTP: 'RESEND_OTP',
    VERIFY_OTP_BUTTON: 'VERIFY_OTP_BUTTON'
}