export const EMAIL_AUTH_CONSTANTS = {
    ENTER_EMAIL_SCREEN: 'ENTER_EMAIL_SCREEN',
    SIGN_IN_SCREEN: 'SIGN_IN_SCREEN',
    SIGN_UP_SCREEN: 'SIGN_UP_SCREEN',
};

export const AUTH_TYPES = {
    EMAIL_SIGN_IN: 'EMAIL_SIGN_IN',
    MOBILE_SIGN_IN: 'MOBILE_SIGN_IN',
};

export const SHOW_WELCOME_BANNER = 'SHOW_WELCOME_BANNER';
export const SHOW = 'SHOW';
