export const AUTOMATION_TEST_ID = {
    CLOSE_ICON: 'CLOSE_ICON',
    MENU_ITEM: 'MENU_ITEM_',
    SIGN_IN_BUTTON: 'SIGN_IN_BUTTON',
    SUBSCRIBE_NOW_BUTTON: 'SUBSCRIBE_NOW_BUTTON',
    ADD_PROFILE:'ADD_PROFILE',
    PROFILE:'PROFILE_',
}