export const LOGIN_ERROR_CODES = {
    LOGIN_NO_USER_FOUND: 'eV2327',
    LOGIN_INVALID_CREDENTIALS: 'eV2134',
    LOGIN_VERIFY_YOUR_ACOUNT: 'eV2371',
};

export const SIGNUP_ERROR_CODES = {
    SIGNUP_USER_ALREADY_EXIST: 'eV1062',
    SIGNUP_ENTER_VALID_EMAIL: 'eV1058',
};
