export const AUTOMATION_TEST_ID = {
    PROFILE: 'PROFILE_',
    ADD_PROFILE: 'ADD_PROFILE',
    MANAGE_PROFILE: 'MANAGE_PROFILE',
    CHECKBOX: 'CHECKBOX_',
    TEXT_BOX_PROFILE_NAME: 'TEXT_BOX_PROFILE_NAME',
    CONTENT_LANGUAGE: 'CONTENT_LANGUAGE',
    APP_LANGUAGE: 'APP_LANGUAGE',
    PROCEED_BUTTON: 'PROCEED_BUTTON',
    REMOVE_PROFILE_BUTTON: 'REMOVE_PROFILE_BUTTON',
    SAVE_BUTTON: 'SAVE_BUTTON',
}