export const AUTOMATION_TEST_ID = {
    DROP_DOWN: 'DROP_DOWN',
    MOBILE_NUMBER_TEXT_INPUT_BOX: 'MOBILE_NUMBER_TEXT_INPUT_BOX',
    SOCIAL_BUTTON_EMAIL: 'SOCIAL_BUTTON_EMAIL',
    SOCIAL_BUTTON_FACEBOOK: 'SOCIAL_BUTTON_FACEBOOK',
    SOCIAL_BUTTON_GOOGLE: 'SOCIAL_BUTTON_GOOGLE',
    PASSWORD_VISIBLE_ICON: 'PASSWORD_VISIBLE_ICON',
    PASSWORD_HIDE_ICON: 'PASSWORD_HIDE_ICON',
    EDIT: 'EDIT',
    OTP_INPUT: 'OTP_INPUT_',
    CLOSE_ICON: 'CLOSE_ICON',
    BACK_NAVIGATION: 'BACK_NAVIGATION',
}